"""Reference/seed data shared between the Alembic migration that ships it to
Postgres and the test fixtures that seed the same rows into SQLite (tests
build tables via `Base.metadata.create_all`, not by running migrations).
"""

# (name, muscle_groups, equipment, instructions, difficulty, exercise_type)
SEED_EXERCISES: list[tuple[str, list[str], str | None, str, str, str]] = [
    ("Barbell Bench Press", ["chest", "triceps", "shoulders"], "barbell",
     "Lower the bar to your mid-chest, then press up until arms are extended.",
     "intermediate", "strength"),
    ("Push-Up", ["chest", "triceps", "shoulders"], "bodyweight",
     "Keep your body in a straight line and lower your chest to the floor, then push back up.",
     "beginner", "strength"),
    ("Incline Dumbbell Press", ["chest", "shoulders"], "dumbbell",
     "On an incline bench, press dumbbells up from shoulder height until arms are extended.",
     "intermediate", "strength"),
    ("Barbell Back Squat", ["quadriceps", "glutes", "hamstrings"], "barbell",
     "Bar on your upper back, squat down until thighs are parallel to the floor, then stand.",
     "intermediate", "strength"),
    ("Bodyweight Squat", ["quadriceps", "glutes"], "bodyweight",
     "Feet shoulder-width apart, squat down keeping your chest up, then stand back up.",
     "beginner", "strength"),
    ("Romanian Deadlift", ["hamstrings", "glutes", "back"], "barbell",
     "Hinge at the hips, lowering the bar along your legs while keeping a slight knee bend.",
     "intermediate", "strength"),
    ("Conventional Deadlift", ["back", "glutes", "hamstrings"], "barbell",
     "Lift the bar from the floor by extending hips and knees together, keeping your back flat.",
     "advanced", "strength"),
    ("Pull-Up", ["back", "biceps"], "bodyweight",
     "Hang from a bar and pull your chin above it, then lower under control.",
     "intermediate", "strength"),
    ("Lat Pulldown", ["back", "biceps"], "machine",
     "Pull the bar down to your upper chest, then let it rise back up under control.",
     "beginner", "strength"),
    ("Bent-Over Barbell Row", ["back", "biceps"], "barbell",
     "Hinge forward and row the bar to your lower ribs, squeezing your shoulder blades.",
     "intermediate", "strength"),
    ("Seated Cable Row", ["back", "biceps"], "machine",
     "Pull the handle to your torso, keeping your back straight, then extend arms back out.",
     "beginner", "strength"),
    ("Overhead Barbell Press", ["shoulders", "triceps"], "barbell",
     "Press the bar from shoulder height straight overhead until arms are extended.",
     "intermediate", "strength"),
    ("Dumbbell Lateral Raise", ["shoulders"], "dumbbell",
     "Raise dumbbells out to your sides until arms are roughly parallel to the floor.",
     "beginner", "strength"),
    ("Barbell Bicep Curl", ["biceps"], "barbell",
     "Curl the bar up toward your shoulders, keeping elbows tucked in.",
     "beginner", "strength"),
    ("Dumbbell Hammer Curl", ["biceps", "forearms"], "dumbbell",
     "Curl dumbbells up with palms facing each other throughout the movement.",
     "beginner", "strength"),
    ("Triceps Pushdown", ["triceps"], "machine",
     "Push the cable attachment down until arms are fully extended, then return under control.",
     "beginner", "strength"),
    ("Close-Grip Bench Press", ["triceps", "chest"], "barbell",
     "Bench press with hands shoulder-width apart to emphasize the triceps.",
     "intermediate", "strength"),
    ("Plank", ["core"], "bodyweight",
     "Hold a straight-body position on your forearms and toes, keeping hips level.",
     "beginner", "strength"),
    ("Hanging Leg Raise", ["core"], "bodyweight",
     "Hang from a bar and raise your legs to hip height or higher, then lower under control.",
     "intermediate", "strength"),
    ("Russian Twist", ["core", "obliques"], "bodyweight",
     "Seated with feet off the floor, rotate your torso side to side.",
     "beginner", "strength"),
    ("Walking Lunge", ["quadriceps", "glutes"], "dumbbell",
     "Step forward into a lunge, alternating legs as you walk.",
     "beginner", "strength"),
    ("Leg Press", ["quadriceps", "glutes", "hamstrings"], "machine",
     "Press the platform away by extending your knees and hips, then return under control.",
     "beginner", "strength"),
    ("Leg Curl", ["hamstrings"], "machine",
     "Curl the pad toward your glutes by bending your knees, then extend back out.",
     "beginner", "strength"),
    ("Leg Extension", ["quadriceps"], "machine",
     "Extend your knees against the pad until legs are straight, then lower under control.",
     "beginner", "strength"),
    ("Standing Calf Raise", ["calves"], "machine",
     "Rise onto your toes as high as possible, then lower your heels below the platform.",
     "beginner", "strength"),
    ("Dumbbell Shoulder Press", ["shoulders", "triceps"], "dumbbell",
     "Press dumbbells from shoulder height straight overhead.",
     "beginner", "strength"),
    ("Face Pull", ["shoulders", "back"], "machine",
     "Pull the rope attachment toward your face, flaring your elbows out wide.",
     "beginner", "strength"),
    ("Barbell Hip Thrust", ["glutes", "hamstrings"], "barbell",
     "With upper back on a bench, drive your hips up until torso is level, then lower.",
     "intermediate", "strength"),
    ("Treadmill Running", ["cardiovascular"], "machine",
     "Maintain a steady running pace for the target duration.",
     "beginner", "cardio"),
    ("Cycling", ["cardiovascular", "quadriceps"], "machine",
     "Maintain a steady pedaling cadence for the target duration.",
     "beginner", "cardio"),
    ("Rowing Machine", ["back", "cardiovascular", "legs"], "machine",
     "Drive with your legs, then pull the handle to your torso, in one fluid motion.",
     "beginner", "cardio"),
    ("Jump Rope", ["cardiovascular", "calves"], "bodyweight",
     "Skip rope at a steady rhythm, landing softly on the balls of your feet.",
     "beginner", "cardio"),
    ("Burpees", ["full_body", "cardiovascular"], "bodyweight",
     "From standing, drop into a push-up, then jump back up explosively.",
     "intermediate", "cardio"),
    ("Mountain Climbers", ["core", "cardiovascular"], "bodyweight",
     "From a plank position, drive your knees toward your chest in a running motion.",
     "beginner", "cardio"),
]
